// hhtools/web/frontend/src/workbench/browser/components/search-field.tsx
import { Search, X } from "lucide-react";
import {
  forwardRef,
  useImperativeHandle,
  useRef,
  type InputHTMLAttributes,
} from "react";

import { cn } from "@/lib/utils";

export interface SearchFieldHandle {
  clear(): void;
  focus(): void;
}

interface SearchFieldProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, "type" | "value"> {
  value: string;
  label: string;
  clearLabel?: string;
  onValueChange(value: string): void;
  onClear?(): void;
}

/** Reusable controlled search field; native input events still reach the
 * compatibility runtime while React remains the source of truth.
 */
export const SearchField = forwardRef<SearchFieldHandle, SearchFieldProps>(
  function SearchField(
    {
      value,
      label,
      clearLabel = "Clear search",
      onValueChange,
      onClear,
      disabled,
      className,
      ...props
    },
    forwardedRef,
  ) {
    const inputRef = useRef<HTMLInputElement>(null);
    const clear = (): void => {
      if (disabled) return;
      onValueChange("");
      onClear?.();
      requestAnimationFrame(() => inputRef.current?.focus());
    };
    useImperativeHandle(forwardedRef, () => ({
      clear,
      focus: () => inputRef.current?.focus(),
    }));

    return (
      <div
        className={cn("search-field", disabled && "disabled", className)}
        role="search"
      >
        <Search
          className="search-field-leading-icon"
          aria-hidden="true"
          data-icon="magnifying-glass"
        />
        <input
          {...props}
          ref={inputRef}
          className="search search-field-input"
          type="search"
          value={value}
          aria-label={label}
          autoComplete={props.autoComplete ?? "off"}
          disabled={disabled}
          spellCheck={false}
          onChange={(event) => onValueChange(event.currentTarget.value)}
        />
        {value && (
          <button
            type="button"
            className="search-field-clear"
            title={clearLabel}
            aria-label={clearLabel}
            disabled={disabled}
            onClick={clear}
          >
            <X aria-hidden="true" data-icon="x-mark" />
          </button>
        )}
      </div>
    );
  },
);

// hhtools/web/frontend/src/components/SearchField.vue
<script setup lang="ts">
import { nextTick, ref } from 'vue'

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<{
  modelValue: string
  label: string
  placeholder?: string
  clearLabel?: string
  autocomplete?: string
  disabled?: boolean
}>(), {
  placeholder: '',
  clearLabel: 'Clear search',
  autocomplete: 'off',
  disabled: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  clear: []
}>()

const input = ref<HTMLInputElement | null>(null)

function updateValue(event: Event): void {
  emit('update:modelValue', (event.currentTarget as HTMLInputElement).value)
}

function focus(): void {
  input.value?.focus()
}

function clear(): void {
  if (props.disabled || !input.value) return

  // Dispatch the same native event as typing. This keeps the component useful
  // with Vue v-model while preserving legacy consumers that listen directly on
  // the real input element (the Motion Library runtime is one such consumer).
  input.value.value = ''
  input.value.dispatchEvent(new Event('input', { bubbles: true }))
  emit('clear')
  void nextTick(focus)
}

defineExpose({ clear, focus })
</script>

<template>
  <div class="search-field" :class="{ disabled }" role="search">
    <!-- Heroicons "magnifying-glass" outline path, MIT licensed. -->
    <svg
      class="search-field-leading-icon"
      data-icon="magnifying-glass"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      aria-hidden="true"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m21 21-4.35-4.35m2.1-5.4a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z" />
    </svg>
    <input
      ref="input"
      v-bind="$attrs"
      class="search search-field-input"
      type="search"
      :value="modelValue"
      :placeholder="placeholder"
      :aria-label="label"
      :autocomplete="autocomplete"
      :disabled="disabled"
      :spellcheck="false"
      @input="updateValue"
    />
    <button
      v-if="modelValue"
      type="button"
      class="search-field-clear"
      :title="clearLabel"
      :aria-label="clearLabel"
      :disabled="disabled"
      @click="clear"
    >
      <!-- Heroicons "x-mark" outline path, MIT licensed. -->
      <svg data-icon="x-mark" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M6 18 18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
</template>
