// hhtools/web/frontend/src/components/BatchWorkflow.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'

import MotionPickerDialog from './MotionPickerDialog.vue'
import SearchField from './SearchField.vue'
import VideoToMotionBatch from './VideoToMotionBatch.vue'
import type { MotionCategory, WorkspaceLocale, WorkspacePanelId } from '../runtime/types'

type BatchCategory = 'all' | MotionCategory
type BatchMode = 'v2m' | 'h2r' | 'r2r'

const props = withDefaults(defineProps<{
  active: boolean
  locale?: WorkspaceLocale
}>(), {
  locale: 'en',
})

const emit = defineEmits<{
  'request-panel': [panel: WorkspacePanelId]
}>()

const pickerOpen = ref(false)
const batchMode = ref<BatchMode>('h2r')
const basketQuery = ref('')
const basketCategory = ref<BatchCategory>('all')

function text(en: string, zh: string): string {
  return props.locale === 'zh-CN' ? zh : en
}

function publishFilter(): void {
  window.dispatchEvent(new CustomEvent('hhtools:batch-filter', {
    detail: {
      query: basketQuery.value,
      category: basketCategory.value,
    },
  }))
}

function handleBasketChanged(): void {
  // Re-publish the current filter after the legacy runtime mutates the list.
  // This keeps the Vue search controls and runtime-rendered rows in sync.
  publishFilter()
}

function importFromMotionWorkspace(): void {
  pickerOpen.value = false
  emit('request-panel', 'motion')
}

function selectBatchMode(mode: BatchMode): void {
  batchMode.value = mode
  pickerOpen.value = false
}

watch([basketQuery, basketCategory], publishFilter)
watch(() => props.active, (active) => {
  if (!active) pickerOpen.value = false
})

onMounted(() => window.addEventListener('hhtools:batch-basket-changed', handleBasketChanged))
onBeforeUnmount(() => window.removeEventListener('hhtools:batch-basket-changed', handleBasketChanged))
</script>

<template>
  <!-- `#stage` belongs to the same App render tree. Vue 3.5's deferred
       Teleport resolves it after the stage has mounted, before the imperative
       runtime binds the stable IDs inside this workspace. -->
  <Teleport defer to="#stage">
    <section
      v-show="active && batchMode === 'h2r'"
      class="batch-stage-workspace"
      :aria-label="text('Batch inputs', '批量输入')"
    >
      <header class="batch-stage-header">
        <div>
          <h1>{{ text('Batch inputs', '批量输入') }}</h1>
          <p>{{ text('Build and validate the clip set before submitting a task.', '先整理并检查动作清单，再提交批量任务。') }}</p>
        </div>
        <div class="batch-stage-count" aria-live="polite">
          <strong id="basket-count">0</strong>
          <span>{{ text('clips', '条动作') }}</span>
        </div>
      </header>

      <div class="batch-stage-toolbar">
        <button id="batch-library-open" type="button" class="btn" @click="pickerOpen = true">
          {{ text('Add from Library', '从资源库添加') }}
        </button>
        <button id="batch-pick-file" type="button" class="btn secondary">
          {{ text('Import file', '导入文件') }}
        </button>
        <button id="batch-pick-folder" type="button" class="btn secondary">
          {{ text('Import folder', '导入文件夹') }}
        </button>
        <SearchField
          id="batch-basket-search"
          v-model="basketQuery"
          :label="text('Search batch inputs', '搜索批量动作')"
          :placeholder="text('Search clips…', '搜索动作……')"
          :clear-label="text('Clear batch search', '清除批量搜索')"
        />
        <select
          id="batch-basket-filter"
          v-model="basketCategory"
          class="search batch-basket-filter"
          :aria-label="text('Filter batch inputs by motion type', '按动作类型筛选批量清单')"
        >
          <option value="all">{{ text('All types', '全部类型') }}</option>
          <option value="motion">{{ text('Motion', '纯动作') }}</option>
          <option value="object">{{ text('Object', '物体交互') }}</option>
          <option value="terrain">{{ text('Terrain', '地形场景') }}</option>
        </select>
      </div>

      <div id="basket-drop" class="batch-basket-frame">
        <div class="batch-basket-columns" aria-hidden="true">
          <span class="batch-basket-check-column"></span>
          <span>{{ text('Clip', '动作') }}</span>
          <span>{{ text('Type', '类型') }}</span>
          <span>{{ text('Reference', '参考骨架') }}</span>
          <span>{{ text('Actions', '操作') }}</span>
        </div>
        <div id="basket-list" class="batch-basket-list" aria-live="polite"></div>
      </div>

      <footer class="batch-stage-footer">
        <label class="batch-select-all">
          <input id="batch-select-all" type="checkbox" />
          <span>{{ text('Select all visible', '全选当前结果') }}</span>
        </label>
        <span id="batch-selected-count" class="batch-selected-count">{{ text('0 selected', '已选择 0 条') }}</span>
        <span class="spacer"></span>
        <button id="batch-remove-selected" type="button" class="btn secondary small" disabled>
          {{ text('Remove selected', '移除所选') }}
        </button>
        <button id="basket-clear" type="button" class="btn secondary small" disabled>
          {{ text('Clear all', '清空全部') }}
        </button>
      </footer>

      <p class="batch-drop-hint">
        {{ text('You can also drop files or folders anywhere in the list.', '也可以把文件或文件夹直接拖入清单区域。') }}
      </p>
    </section>
  </Teleport>

  <Teleport defer to="#stage">
    <section
      v-show="active && batchMode === 'r2r'"
      class="batch-stage-workspace r2r-batch-stage-workspace"
      :aria-label="text('R2R batch inputs', 'R2R 批量输入')"
    >
      <header class="batch-stage-header">
        <div>
          <h1>{{ text('Robot trajectory inputs', '机器人轨迹输入') }}</h1>
          <p>{{ text('Build a robot-trajectory set for one source and target robot pair.', '为同一组源机器人和目标机器人整理待转换轨迹。') }}</p>
        </div>
        <div class="batch-stage-count" aria-live="polite">
          <strong id="r2r-basket-count">0</strong>
          <span>{{ text('trajectories', '条轨迹') }}</span>
        </div>
      </header>

      <div class="batch-stage-toolbar r2r-batch-stage-toolbar">
        <button id="r2r-batch-pick-file" type="button" class="btn secondary">
          {{ text('Import file', '导入文件') }}
        </button>
        <button id="r2r-batch-pick-folder" type="button" class="btn secondary">
          {{ text('Import folder', '导入文件夹') }}
        </button>
      </div>

      <div id="r2r-basket-drop" class="batch-basket-frame r2r-batch-basket-frame">
        <div class="batch-basket-columns r2r-batch-basket-columns" aria-hidden="true">
          <span>{{ text('Trajectory', '轨迹') }}</span>
          <span>{{ text('Profile', '类型') }}</span>
          <span>{{ text('Actions', '操作') }}</span>
        </div>
        <div id="r2r-basket-list" class="batch-basket-list" aria-live="polite"></div>
      </div>

      <footer class="batch-stage-footer">
        <span id="r2r-batch-stage-summary" class="batch-selected-count">
          {{ text('No robot trajectories selected', '尚未选择机器人轨迹') }}
        </span>
        <span class="spacer"></span>
        <button id="r2r-basket-clear" type="button" class="btn secondary small" disabled>
          {{ text('Clear all', '清空全部') }}
        </button>
      </footer>

      <p class="batch-drop-hint">
        {{ text('Drop robot-trajectory files or folders anywhere in the list.', '也可以把机器人轨迹文件或文件夹直接拖入清单。') }}
      </p>
    </section>
  </Teleport>

  <div class="panel-stack batch-workflow-stack">
    <h2>{{ text('Batch', '批量处理') }}</h2>

    <div
      class="motion-profile-switcher batch-mode-switcher"
      role="radiogroup"
      :aria-label="text('Batch workflow', '批量工作流')"
    >
      <label class="motion-profile-selector">
        <input
          class="sr-only"
          type="radio"
          name="batch-workflow-mode"
          value="v2m"
          :checked="batchMode === 'v2m'"
          @change="selectBatchMode('v2m')"
        />
        <span class="motion-profile-selector-content">V2M</span>
      </label>
      <label class="motion-profile-selector">
        <input
          class="sr-only"
          type="radio"
          name="batch-workflow-mode"
          value="h2r"
          :checked="batchMode === 'h2r'"
          @change="selectBatchMode('h2r')"
        />
        <span class="motion-profile-selector-content">H2R</span>
      </label>
      <label class="motion-profile-selector">
        <input
          class="sr-only"
          type="radio"
          name="batch-workflow-mode"
          value="r2r"
          :checked="batchMode === 'r2r'"
          @change="selectBatchMode('r2r')"
        />
        <span class="motion-profile-selector-content">R2R</span>
      </label>
    </div>

    <VideoToMotionBatch
      :active="active && batchMode === 'v2m'"
      :locale="locale"
    />

    <div v-show="batchMode === 'h2r'" class="batch-mode-content">

    <div class="batch-step-summary">
      <span>{{ text('1. Inputs', '1. 输入动作') }}</span>
      <strong><span id="batch-inspector-count">0</span> {{ text('clips', '条') }}</strong>
    </div>

    <details class="video-workflow-step" open>
      <summary class="video-workflow-step-summary">
        <span>{{ text('2. Target robot & compatibility', '2. 目标机器人与兼容性') }}</span>
      </summary>
      <div class="video-workflow-step-body workflow-compact-controls">
        <div class="workflow-picker-row">
          <select
            id="batch-robot-select"
            class="search"
            :aria-label="text('Select target robot', '选择目标机器人')"
          ></select>
          <button type="button" class="btn secondary small" @click="emit('request-panel', 'robot-assets')">
            {{ text('Import robot', '导入机器人') }}
          </button>
        </div>
        <button id="batch-robot-load" type="button" class="btn workflow-load-button" disabled>
          {{ text('Load target robot', '加载目标机器人') }}
        </button>
        <p id="batch-robot" class="workflow-status-line" role="status">{{ text('Not loaded', '未加载') }}</p>
        <div id="batch-ref-hint" class="batch-compatibility-list" aria-live="polite"></div>
      </div>
    </details>

    <details class="video-workflow-step" open>
      <summary class="video-workflow-step-summary">
        <span>{{ text('3. Run settings', '3. 运行设置') }}</span>
      </summary>
      <div class="video-workflow-step-body workflow-compact-controls">
        <div class="workflow-field-grid">
          <label class="video-workflow-field">
            <span class="k">{{ text('Solver', '求解器') }}</span>
            <select id="batch-backend" class="search">
              <option value="newton">Newton IK</option>
              <option value="interaction_mesh">Interaction-Mesh</option>
            </select>
          </label>
          <label class="video-workflow-field">
            <span class="k">{{ text('Output format', '输出格式') }}</span>
            <select id="batch-format" class="search">
              <option value="pkl">PKL</option>
              <option value="csv">CSV</option>
            </select>
          </label>
        </div>
        <p id="batch-settings-note" class="batch-settings-note"></p>

        <details class="batch-advanced-settings">
          <summary>{{ text('Advanced settings', '高级设置') }}</summary>
          <div class="batch-advanced-settings-body">
            <label class="video-workflow-field" id="batch-size-field">
              <span class="k">{{ text('GPU batch size', 'GPU 批大小') }}</span>
              <input id="batch-size" class="search" type="number" min="1" max="256" step="1" :placeholder="text('Auto (default 16)', '自动（默认 16）')" />
              <small>{{ text('The server may lower this value for the selected robot and device.', '服务器会根据机器人与设备能力自动下调。') }}</small>
            </label>
            <div class="workflow-field-grid">
              <label class="video-workflow-field">
                <span class="k">Retarget FPS</span>
                <input id="batch-retarget-fps" class="search" type="number" min="1" step="1" :placeholder="text('Original', '原始帧率')" />
              </label>
              <label class="video-workflow-field">
                <span class="k">Export FPS</span>
                <input id="batch-export-fps" class="search" type="number" min="1" step="1" :placeholder="text('Same as Retarget', '与 Retarget 相同')" />
              </label>
            </div>
            <div class="workflow-field-grid">
              <label class="video-workflow-field">
                <span class="k">{{ text('Start (s)', '起始 (s)') }}</span>
                <input id="batch-export-t-start" class="search" type="number" min="0" step="0.01" placeholder="0" />
              </label>
              <label class="video-workflow-field">
                <span class="k">{{ text('End (s)', '截止 (s)') }}</span>
                <input id="batch-export-t-end" class="search" type="number" min="0" step="0.01" :placeholder="text('End of each clip', '每条动作结尾')" />
              </label>
            </div>
            <label id="batch-csv-header-row" class="workflow-checkbox-row">
              <input id="batch-csv-header" type="checkbox" checked />
              <span>{{ text('Include CSV comments and column headers', 'CSV 含注释与列名表头') }}</span>
            </label>
            <label class="video-workflow-field">
              <span class="k">{{ text('Result name', '结果名称') }}</span>
              <input id="batch-out" class="search" value="batch_export" :placeholder="text('ZIP filename', 'ZIP 文件名')" />
            </label>
          </div>
        </details>
      </div>
    </details>

    <section class="batch-run-panel" aria-labelledby="batch-run-title">
      <div class="batch-run-heading">
        <h3 id="batch-run-title">{{ text('4. Run', '4. 执行') }}</h3>
        <span class="batch-task-note">{{ text('Continues in Tasks', '任务会在底部继续运行') }}</span>
      </div>
      <p id="batch-run-summary" class="batch-run-summary">{{ text('No inputs selected.', '尚未选择输入动作。') }}</p>
      <button id="batch-run" type="button" class="btn" disabled>
        {{ text('Start batch task', '开始批量任务') }}
      </button>
      <p id="batch-disabled-reason" class="disabled-action-reason" role="status">
        {{ text('Add motions and select a target robot first.', '请先添加动作并选择目标机器人。') }}
      </p>

      <div id="batch-progress-stack" class="batch-progress-stack hidden">
        <div class="batch-progress-row">
          <span class="batch-progress-label">{{ text('Overall', '总进度') }}</span>
          <div id="batch-progress-total" class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar"></div></div>
        </div>
        <div class="batch-progress-row">
          <span class="batch-progress-label">{{ text('Current', '当前批次') }}</span>
          <div id="batch-progress-clip" class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar"></div></div>
        </div>
      </div>
      <p id="batch-status" class="workflow-status-line" role="status" aria-live="polite"></p>

      <div id="batch-result-card" class="batch-result-card hidden" aria-live="polite">
        <strong id="batch-result-title">{{ text('Batch complete', '批量任务完成') }}</strong>
        <p id="batch-result-summary"></p>
        <div class="workflow-button-row">
          <button id="batch-result-download" type="button" class="btn secondary small">
            {{ text('Download ZIP', '下载 ZIP') }}
          </button>
          <button id="batch-result-retry" type="button" class="btn secondary small" hidden>
            {{ text('Retry failed only', '仅重试失败项') }}
          </button>
          <button id="batch-result-tasks" type="button" class="btn secondary small">
            {{ text('Open Tasks', '打开任务面板') }}
          </button>
        </div>
      </div>
      <div id="batch-failures" class="batch-failures hidden"></div>
    </section>

    <MotionPickerDialog
      :open="pickerOpen"
      :locale="locale"
      mode="basket"
      asset-kind="human_motion"
      @close="pickerOpen = false"
      @import="importFromMotionWorkspace"
    />
    </div>

    <div v-show="batchMode === 'r2r'" class="batch-mode-content">
      <div class="batch-step-summary">
        <span>{{ text('1. Source trajectories', '1. 源轨迹') }}</span>
        <strong><span id="r2r-batch-inspector-count">0</span> {{ text('trajectories', '条') }}</strong>
      </div>

      <details class="video-workflow-step" open>
        <summary class="video-workflow-step-summary">
          <span>{{ text('2. Source robot', '2. 源机器人') }}</span>
        </summary>
        <div class="video-workflow-step-body workflow-compact-controls">
          <div class="workflow-picker-row">
            <select
              id="r2r-batch-source-select"
              class="search"
              :aria-label="text('Select source robot', '选择源机器人')"
            ></select>
            <button type="button" class="btn secondary small" @click="emit('request-panel', 'robot-assets')">
              {{ text('Import robot', '导入机器人') }}
            </button>
          </div>
          <button id="r2r-batch-source-load" type="button" class="btn workflow-load-button">
            {{ text('Load source robot', '加载源机器人') }}
          </button>
          <p id="r2r-batch-source-status" class="workflow-status-line" role="status">
            {{ text('Not loaded', '未加载') }}
          </p>
        </div>
      </details>

      <details class="video-workflow-step" open>
        <summary class="video-workflow-step-summary">
          <span>{{ text('3. Target robot', '3. 目标机器人') }}</span>
        </summary>
        <div class="video-workflow-step-body workflow-compact-controls">
          <div class="workflow-picker-row">
            <select
              id="r2r-batch-target-select"
              class="search"
              :aria-label="text('Select target robot', '选择目标机器人')"
            ></select>
            <button type="button" class="btn secondary small" @click="emit('request-panel', 'robot-assets')">
              {{ text('Import robot', '导入机器人') }}
            </button>
          </div>
          <button id="r2r-batch-target-load" type="button" class="btn workflow-load-button">
            {{ text('Load target robot', '加载目标机器人') }}
          </button>
          <p id="r2r-batch-target-status" class="workflow-status-line" role="status">
            {{ text('Not loaded', '未加载') }}
          </p>
          <p id="r2r-batch-calibration-status" class="workflow-status-line" role="status"></p>
        </div>
      </details>

      <details class="video-workflow-step" open>
        <summary class="video-workflow-step-summary">
          <span>{{ text('4. Run settings', '4. 运行设置') }}</span>
        </summary>
        <div class="video-workflow-step-body workflow-compact-controls">
          <div class="workflow-field-grid">
            <label class="video-workflow-field">
              <span class="k">{{ text('Solver', '求解器') }}</span>
              <select id="r2r-batch-backend" class="search">
                <option value="newton">Newton IK</option>
                <option value="interaction_mesh">Interaction-Mesh</option>
              </select>
            </label>
            <label class="video-workflow-field">
              <span class="k">{{ text('Output format', '输出格式') }}</span>
              <select id="r2r-batch-format" class="search">
                <option value="csv">CSV</option>
                <option value="pkl">PKL</option>
              </select>
            </label>
          </div>

          <details class="batch-advanced-settings">
            <summary>{{ text('Advanced settings', '高级设置') }}</summary>
            <div class="batch-advanced-settings-body">
              <div class="workflow-field-grid">
                <label class="video-workflow-field">
                  <span class="k">{{ text('Source FPS', '源轨迹 FPS') }}</span>
                  <input id="r2r-batch-source-fps" class="search" type="number" min="1" step="1" value="50" />
                </label>
                <label class="video-workflow-field">
                  <span class="k">Retarget FPS</span>
                  <input id="r2r-batch-retarget-fps" class="search" type="number" min="1" step="1" :placeholder="text('Source FPS', '与源轨迹相同')" />
                </label>
              </div>
              <label class="video-workflow-field">
                <span class="k">Export FPS</span>
                <input id="r2r-batch-export-fps" class="search" type="number" min="1" step="1" :placeholder="text('Same as Retarget', '与 Retarget 相同')" />
              </label>
              <div class="workflow-field-grid">
                <label class="video-workflow-field">
                  <span class="k">{{ text('Start (s)', '起始 (s)') }}</span>
                  <input id="r2r-batch-t-start" class="search" type="number" min="0" step="0.01" placeholder="0" />
                </label>
                <label class="video-workflow-field">
                  <span class="k">{{ text('End (s)', '截止 (s)') }}</span>
                  <input id="r2r-batch-t-end" class="search" type="number" min="0" step="0.01" :placeholder="text('End of each trajectory', '每条轨迹结尾')" />
                </label>
              </div>
              <label class="workflow-checkbox-row">
                <input id="r2r-batch-csv-header" type="checkbox" checked />
                <span>{{ text('Include CSV comments and column headers', 'CSV 含注释与列名表头') }}</span>
              </label>
              <label class="video-workflow-field">
                <span class="k">{{ text('Result name', '结果名称') }}</span>
                <input id="r2r-batch-out" class="search" value="r2r_batch_export" :placeholder="text('ZIP filename', 'ZIP 文件名')" />
              </label>
            </div>
          </details>
        </div>
      </details>

      <section class="batch-run-panel" aria-labelledby="r2r-batch-run-title">
        <div class="batch-run-heading">
          <h3 id="r2r-batch-run-title">{{ text('5. Run', '5. 执行') }}</h3>
          <span class="batch-task-note">{{ text('Continues in Tasks', '任务会在底部继续运行') }}</span>
        </div>
        <p id="r2r-batch-run-summary" class="batch-run-summary">
          {{ text('No source trajectories selected.', '尚未选择源轨迹。') }}
        </p>
        <button id="r2r-batch-run" type="button" class="btn" disabled>
          {{ text('Start R2R batch task', '开始 R2R 批量任务') }}
        </button>
        <p id="r2r-batch-disabled-reason" class="disabled-action-reason" role="status">
          {{ text('Add trajectories and load both robots first.', '请先添加轨迹并加载源机器人和目标机器人。') }}
        </p>
        <div id="r2r-batch-progress" class="progress video-workflow-progress" style="display:none"><div class="bar"></div></div>
        <p id="r2r-batch-status" class="workflow-status-line" role="status" aria-live="polite"></p>
      </section>
    </div>
  </div>
</template>

// hhtools/web/frontend/src/workbench/browser/components/batch-workflow.tsx
import { useEffect, useState } from "react";

import { useLocaleText } from "@/hooks/use-locale-text";
import type {
  MotionCategory,
  WorkspaceLocale,
  WorkspacePanelId,
} from "@/runtime/types";
import { MotionPickerDialog } from "./motion-picker-dialog";
import { SearchField } from "./search-field";
import type { VideoBatchModel, VideoBatchStatus } from "../use-video-batch";

export type BatchMode = "v2m" | "h2r" | "r2r";

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 ** 2).toFixed(1)} MB`;
}

function videoStatusLabel(
  status: VideoBatchStatus,
  locale: WorkspaceLocale,
): string {
  const labels: Record<VideoBatchStatus, [string, string]> = {
    queued: ["Queued", "等待处理"],
    uploading: ["Uploading", "正在上传"],
    running: ["Generating motion", "正在生成动作"],
    done: ["Motion ready", "动作已生成"],
    error: ["Failed", "处理失败"],
  };
  return labels[status][locale === "zh-CN" ? 1 : 0];
}

export function BatchStage({
  active,
  mode,
  locale,
  videoBatch,
}: {
  active: boolean;
  mode: BatchMode;
  locale: WorkspaceLocale;
  videoBatch: VideoBatchModel;
}) {
  return (
    <>
      <div style={{ display: active && mode === "v2m" ? undefined : "none" }}>
        <VideoBatchStage locale={locale} model={videoBatch} />
      </div>
      <div style={{ display: active && mode === "h2r" ? undefined : "none" }}>
        <HumanBatchStage locale={locale} />
      </div>
      <div style={{ display: active && mode === "r2r" ? undefined : "none" }}>
        <RobotBatchStage locale={locale} />
      </div>
    </>
  );
}

function RobotBatchStage({ locale }: { locale: WorkspaceLocale }) {
  const text = useLocaleText(locale);
  return (
    <section
      className="batch-stage-workspace r2r-batch-stage-workspace"
      aria-label={text("R2R batch inputs", "R2R 批量输入")}
    >
      <header className="batch-stage-header">
        <div>
          <h1>{text("Robot trajectory inputs", "机器人轨迹输入")}</h1>
          <p>
            {text(
              "Build a trajectory set for one source and target robot pair.",
              "为同一组源机器人和目标机器人整理待转换轨迹。",
            )}
          </p>
        </div>
        <div className="batch-stage-count">
          <strong id="r2r-basket-count">0</strong>
          <span>{text("trajectories", "条轨迹")}</span>
        </div>
      </header>
      <div className="batch-stage-toolbar r2r-batch-stage-toolbar">
        <button
          id="r2r-batch-pick-file"
          type="button"
          className="btn secondary"
        >
          {text("Import file", "导入文件")}
        </button>
        <button
          id="r2r-batch-pick-folder"
          type="button"
          className="btn secondary"
        >
          {text("Import folder", "导入文件夹")}
        </button>
      </div>
      <div
        id="r2r-basket-drop"
        className="batch-basket-frame r2r-batch-basket-frame"
      >
        <div
          className="batch-basket-columns r2r-batch-basket-columns"
          aria-hidden="true"
        >
          <span>{text("Trajectory", "轨迹")}</span>
          <span>{text("Profile", "类型")}</span>
          <span>{text("Actions", "操作")}</span>
        </div>
        <div
          id="r2r-basket-list"
          className="batch-basket-list"
          aria-live="polite"
        />
      </div>
      <footer className="batch-stage-footer">
        <span id="r2r-batch-stage-summary" className="batch-selected-count">
          {text("No robot trajectories selected", "尚未选择机器人轨迹")}
        </span>
        <span className="spacer" />
        <button
          id="r2r-basket-clear"
          type="button"
          className="btn secondary small"
          disabled
        >
          {text("Clear all", "清空全部")}
        </button>
      </footer>
    </section>
  );
}

function HumanBatchStage({ locale }: { locale: WorkspaceLocale }) {
  const text = useLocaleText(locale);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<"all" | MotionCategory>("all");
  useEffect(() => {
    window.dispatchEvent(
      new CustomEvent("hhtools:batch-filter", { detail: { query, category } }),
    );
  }, [category, query]);
  return (
    <section
      className="batch-stage-workspace"
      aria-label={text("Batch inputs", "批量输入")}
    >
      <header className="batch-stage-header">
        <div>
          <h1>{text("Batch inputs", "批量输入")}</h1>
          <p>
            {text(
              "Build and validate the clip set before submitting a task.",
              "先整理并检查动作清单，再提交批量任务。",
            )}
          </p>
        </div>
        <div className="batch-stage-count">
          <strong id="basket-count">0</strong>
          <span>{text("clips", "条动作")}</span>
        </div>
      </header>
      <div className="batch-stage-toolbar">
        <button
          id="batch-library-open"
          type="button"
          className="btn"
          onClick={() =>
            window.dispatchEvent(new Event("hhtools:batch-library-request"))
          }
        >
          {text("Add from Library", "从资源库添加")}
        </button>
        <button id="batch-pick-file" type="button" className="btn secondary">
          {text("Import file", "导入文件")}
        </button>
        <button id="batch-pick-folder" type="button" className="btn secondary">
          {text("Import folder", "导入文件夹")}
        </button>
        <SearchField
          id="batch-basket-search"
          value={query}
          onValueChange={setQuery}
          label={text("Search batch inputs", "搜索批量动作")}
          placeholder={text("Search clips…", "搜索动作……")}
        />
        <select
          id="batch-basket-filter"
          value={category}
          className="search batch-basket-filter"
          onChange={(event) =>
            setCategory(event.currentTarget.value as "all" | MotionCategory)
          }
        >
          <option value="all">{text("All types", "全部类型")}</option>
          <option value="motion">{text("Motion", "纯动作")}</option>
          <option value="object">{text("Object", "物体交互")}</option>
          <option value="terrain">{text("Terrain", "地形场景")}</option>
        </select>
      </div>
      <div id="basket-drop" className="batch-basket-frame">
        <div className="batch-basket-columns" aria-hidden="true">
          <span className="batch-basket-check-column" />
          <span>{text("Clip", "动作")}</span>
          <span>{text("Type", "类型")}</span>
          <span>{text("Reference", "参考骨架")}</span>
          <span>{text("Actions", "操作")}</span>
        </div>
        <div
          id="basket-list"
          className="batch-basket-list"
          aria-live="polite"
        />
      </div>
      <footer className="batch-stage-footer">
        <label className="batch-select-all">
          <input id="batch-select-all" type="checkbox" />
          <span>{text("Select all visible", "全选当前结果")}</span>
        </label>
        <span id="batch-selected-count" className="batch-selected-count">
          {text("0 selected", "已选择 0 条")}
        </span>
        <span className="spacer" />
        <button
          id="batch-remove-selected"
          type="button"
          className="btn secondary small"
          disabled
        >
          {text("Remove selected", "移除所选")}
        </button>
        <button
          id="basket-clear"
          type="button"
          className="btn secondary small"
          disabled
        >
          {text("Clear all", "清空全部")}
        </button>
      </footer>
    </section>
  );
}

function VideoBatchStage({
  locale,
  model,
}: {
  locale: WorkspaceLocale;
  model: VideoBatchModel;
}) {
  const text = useLocaleText(locale);
  return (
    <section className="batch-stage-workspace v2m-batch-stage-workspace">
      <header className="batch-stage-header">
        <div>
          <h1>{text("Video inputs", "视频输入")}</h1>
          <p>
            {text(
              "Each video becomes an independent GVHMR task.",
              "每个视频会作为一项独立的 GVHMR 任务处理。",
            )}
          </p>
        </div>
        <div className="batch-stage-count">
          <strong id="v2m-batch-count">{model.videos.length}</strong>
          <span>{text("videos", "个视频")}</span>
        </div>
      </header>
      <div className="batch-stage-toolbar">
        <button
          id="v2m-batch-pick-files"
          type="button"
          className="btn"
          disabled={model.busy}
          onClick={() => void model.pickVideos(false)}
        >
          {text("Import videos", "导入视频")}
        </button>
        <button
          id="v2m-batch-pick-folder"
          type="button"
          className="btn secondary"
          disabled={model.busy}
          onClick={() => void model.pickVideos(true)}
        >
          {text("Import folder", "导入文件夹")}
        </button>
      </div>
      <div
        id="v2m-batch-drop"
        className="batch-basket-frame v2m-batch-frame"
        onDragEnter={(event) => event.preventDefault()}
        onDragOver={(event) => event.preventDefault()}
        onDrop={(event) => {
          event.preventDefault();
          void model.dropVideos(event.dataTransfer);
        }}
      >
        <div id="v2m-batch-list" className="batch-basket-list">
          {model.videos.length === 0 && (
            <div className="batch-basket-empty">
              <strong>{text("Add videos to begin", "添加视频以开始")}</strong>
            </div>
          )}
          {model.videos.map((item) => (
            <div key={item.id} className="v2m-batch-row">
              <div className="batch-basket-main">
                <strong className="batch-basket-name">{item.file.name}</strong>
                <small className="batch-basket-meta">
                  {item.file._relpath ||
                    item.file.webkitRelativePath ||
                    item.file.name}
                </small>
              </div>
              <span className="batch-basket-reference">
                {formatBytes(item.file.size)}
              </span>
              <div className="v2m-batch-status">
                <span className={`v2m-batch-state is-${item.status}`}>
                  {videoStatusLabel(item.status, locale)}
                </span>
                {item.message && <small>{item.message}</small>}
                {item.progress > 0 && item.progress < 1 && (
                  <div className="progress">
                    <div
                      className="bar"
                      style={{ width: `${Math.round(item.progress * 100)}%` }}
                    />
                  </div>
                )}
              </div>
              <div className="batch-basket-actions">
                <button
                  type="button"
                  className="batch-basket-remove"
                  aria-label={text(
                    `Remove ${item.file.name}`,
                    `移除 ${item.file.name}`,
                  )}
                  disabled={model.busy}
                  onClick={() => model.removeVideo(item.id)}
                >
                  ×
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
      <footer className="batch-stage-footer">
        <span className="batch-selected-count">
          {text(
            `${model.completedCount} ready · ${model.errorCount} failed`,
            `已完成 ${model.completedCount} 个 · 失败 ${model.errorCount} 个`,
          )}
        </span>
        <span className="spacer" />
        <button
          type="button"
          className="btn secondary small"
          disabled={model.busy || model.videos.length === 0}
          onClick={model.clearVideos}
        >
          {text("Clear all", "清空全部")}
        </button>
      </footer>
    </section>
  );
}

export function BatchWorkflow({
  mode,
  onModeChange,
  locale,
  onRequestPanel,
  videoBatch,
}: {
  mode: BatchMode;
  onModeChange(mode: BatchMode): void;
  locale: WorkspaceLocale;
  onRequestPanel(panel: WorkspacePanelId): void;
  videoBatch: VideoBatchModel;
}) {
  const text = useLocaleText(locale);
  const [pickerOpen, setPickerOpen] = useState(false);
  useEffect(() => {
    const openPicker = () => setPickerOpen(true);
    window.addEventListener("hhtools:batch-library-request", openPicker);
    return () =>
      window.removeEventListener("hhtools:batch-library-request", openPicker);
  }, []);
  return (
    <div className="panel-stack batch-workflow-stack">
      <h2>{text("Batch", "批量处理")}</h2>
      <div
        className="motion-profile-switcher batch-mode-switcher"
        role="radiogroup"
        aria-label={text("Batch workflow", "批量工作流")}
      >
        {(["v2m", "h2r", "r2r"] as const).map((item) => (
          <label key={item} className="motion-profile-selector">
            <input
              className="sr-only"
              type="radio"
              name="batch-workflow-mode"
              value={item}
              checked={mode === item}
              onChange={() => onModeChange(item)}
            />
            <span className="motion-profile-selector-content">
              {item.toUpperCase()}
            </span>
          </label>
        ))}
      </div>
      <div style={{ display: mode === "v2m" ? undefined : "none" }}>
        <VideoBatchInspector locale={locale} model={videoBatch} />
      </div>
      <div style={{ display: mode === "h2r" ? undefined : "none" }}>
        <HumanBatchInspector locale={locale} onRequestPanel={onRequestPanel} />
      </div>
      <div style={{ display: mode === "r2r" ? undefined : "none" }}>
        <RobotBatchInspector locale={locale} onRequestPanel={onRequestPanel} />
      </div>
      <MotionPickerDialog
        open={pickerOpen}
        locale={locale}
        mode="basket"
        onClose={() => setPickerOpen(false)}
        onImport={() => {
          setPickerOpen(false);
          onRequestPanel("motion");
        }}
      />
    </div>
  );
}

function HumanBatchInspector({
  locale,
  onRequestPanel,
}: {
  locale: WorkspaceLocale;
  onRequestPanel(panel: WorkspacePanelId): void;
}) {
  const text = useLocaleText(locale);
  return (
    <div className="batch-mode-content">
      <div className="batch-step-summary">
        <span>{text("1. Inputs", "1. 输入动作")}</span>
        <strong>
          <span id="batch-inspector-count">0</span> {text("clips", "条")}
        </strong>
      </div>
      <details className="video-workflow-step" open>
        <summary className="video-workflow-step-summary">
          <span>
            {text("2. Target robot & compatibility", "2. 目标机器人与兼容性")}
          </span>
        </summary>
        <div className="video-workflow-step-body workflow-compact-controls">
          <div className="workflow-picker-row">
            <select id="batch-robot-select" className="search" />
            <button
              type="button"
              className="btn secondary small"
              onClick={() => onRequestPanel("robot-assets")}
            >
              {text("Import robot", "导入机器人")}
            </button>
          </div>
          <button
            id="batch-robot-load"
            type="button"
            className="btn workflow-load-button"
            disabled
          >
            {text("Load target robot", "加载目标机器人")}
          </button>
          <p id="batch-robot" className="workflow-status-line">
            {text("Not loaded", "未加载")}
          </p>
          <div id="batch-ref-hint" className="batch-compatibility-list" />
        </div>
      </details>
      <BatchSettings locale={locale} prefix="batch" />
      <BatchRun locale={locale} prefix="batch" />
    </div>
  );
}

function RobotBatchInspector({
  locale,
  onRequestPanel,
}: {
  locale: WorkspaceLocale;
  onRequestPanel(panel: WorkspacePanelId): void;
}) {
  const text = useLocaleText(locale);
  const robot = (kind: "source" | "target") => (
    <details className="video-workflow-step" open>
      <summary className="video-workflow-step-summary">
        <span>
          {text(
            kind === "source" ? "2. Source robot" : "3. Target robot",
            kind === "source" ? "2. 源机器人" : "3. 目标机器人",
          )}
        </span>
      </summary>
      <div className="video-workflow-step-body workflow-compact-controls">
        <div className="workflow-picker-row">
          <select id={`r2r-batch-${kind}-select`} className="search" />
          <button
            type="button"
            className="btn secondary small"
            onClick={() => onRequestPanel("robot-assets")}
          >
            {text("Import robot", "导入机器人")}
          </button>
        </div>
        <button
          id={`r2r-batch-${kind}-load`}
          type="button"
          className="btn workflow-load-button"
        >
          {text(
            `Load ${kind} robot`,
            `加载${kind === "source" ? "源" : "目标"}机器人`,
          )}
        </button>
        <p id={`r2r-batch-${kind}-status`} className="workflow-status-line">
          {text("Not loaded", "未加载")}
        </p>
        {kind === "target" && (
          <p
            id="r2r-batch-calibration-status"
            className="workflow-status-line"
          />
        )}
      </div>
    </details>
  );
  return (
    <div className="batch-mode-content">
      <div className="batch-step-summary">
        <span>{text("1. Source trajectories", "1. 源轨迹")}</span>
        <strong>
          <span id="r2r-batch-inspector-count">0</span>{" "}
          {text("trajectories", "条")}
        </strong>
      </div>
      {robot("source")}
      {robot("target")}
      <BatchSettings locale={locale} prefix="r2r-batch" />
      <BatchRun locale={locale} prefix="r2r-batch" />
    </div>
  );
}

function BatchSettings({
  locale,
  prefix,
}: {
  locale: WorkspaceLocale;
  prefix: "batch" | "r2r-batch";
}) {
  const text = useLocaleText(locale);
  const r2r = prefix === "r2r-batch";
  return (
    <details className="video-workflow-step" open>
      <summary className="video-workflow-step-summary">
        <span>
          {text(
            r2r ? "4. Run settings" : "3. Run settings",
            r2r ? "4. 运行设置" : "3. 运行设置",
          )}
        </span>
      </summary>
      <div className="video-workflow-step-body workflow-compact-controls">
        <div className="workflow-field-grid">
          <label className="video-workflow-field">
            <span className="k">{text("Solver", "求解器")}</span>
            <select id={`${prefix}-backend`} className="search">
              <option value="newton">Newton IK</option>
              <option value="interaction_mesh">Interaction-Mesh</option>
            </select>
          </label>
          <label className="video-workflow-field">
            <span className="k">{text("Output format", "输出格式")}</span>
            <select id={`${prefix}-format`} className="search">
              <option value="pkl">PKL</option>
              <option value="csv">CSV</option>
            </select>
          </label>
        </div>
        {!r2r && <p id="batch-settings-note" className="batch-settings-note" />}
        <details className="batch-advanced-settings">
          <summary>{text("Advanced settings", "高级设置")}</summary>
          <div className="batch-advanced-settings-body">
            {!r2r && (
              <label className="video-workflow-field" id="batch-size-field">
                <span className="k">
                  {text("GPU batch size", "GPU 批大小")}
                </span>
                <input
                  id="batch-size"
                  className="search"
                  type="number"
                  min="1"
                  max="256"
                />
              </label>
            )}
            <div className="workflow-field-grid">
              {r2r && (
                <label className="video-workflow-field">
                  <span className="k">Source FPS</span>
                  <input
                    id="r2r-batch-source-fps"
                    className="search"
                    type="number"
                    min="1"
                    defaultValue="50"
                  />
                </label>
              )}
              <label className="video-workflow-field">
                <span className="k">Retarget FPS</span>
                <input
                  id={`${prefix}-retarget-fps`}
                  className="search"
                  type="number"
                  min="1"
                />
              </label>
            </div>
            <label className="video-workflow-field">
              <span className="k">Export FPS</span>
              <input
                id={`${prefix}-export-fps`}
                className="search"
                type="number"
                min="1"
              />
            </label>
            <div className="workflow-field-grid">
              <label className="video-workflow-field">
                <span className="k">{text("Start (s)", "起始 (s)")}</span>
                <input
                  id={r2r ? "r2r-batch-t-start" : "batch-export-t-start"}
                  className="search"
                  type="number"
                  min="0"
                  defaultValue="0"
                />
              </label>
              <label className="video-workflow-field">
                <span className="k">{text("End (s)", "截止 (s)")}</span>
                <input
                  id={r2r ? "r2r-batch-t-end" : "batch-export-t-end"}
                  className="search"
                  type="number"
                  min="0"
                />
              </label>
            </div>
            <label
              id={r2r ? undefined : "batch-csv-header-row"}
              className="workflow-checkbox-row"
            >
              <input
                id={`${prefix}-csv-header`}
                type="checkbox"
                defaultChecked
              />
              <span>{text("Include CSV header", "CSV 含表头")}</span>
            </label>
            <label className="video-workflow-field">
              <span className="k">{text("Result name", "结果名称")}</span>
              <input
                id={`${prefix}-out`}
                className="search"
                defaultValue={r2r ? "r2r_batch_export" : "batch_export"}
              />
            </label>
          </div>
        </details>
      </div>
    </details>
  );
}

function BatchRun({
  locale,
  prefix,
}: {
  locale: WorkspaceLocale;
  prefix: "batch" | "r2r-batch";
}) {
  const text = useLocaleText(locale);
  const r2r = prefix === "r2r-batch";
  if (r2r)
    return (
      <section className="batch-run-panel">
        <p id="r2r-batch-run-summary" className="batch-run-summary">
          {text("No source trajectories selected.", "尚未选择源轨迹。")}
        </p>
        <button id="r2r-batch-run" type="button" className="btn" disabled>
          {text("Start R2R batch task", "开始 R2R 批量任务")}
        </button>
        <p id="r2r-batch-disabled-reason" className="disabled-action-reason">
          {text(
            "Add trajectories and load both robots first.",
            "请先添加轨迹并加载源机器人和目标机器人。",
          )}
        </p>
        <div
          id="r2r-batch-progress"
          className="progress"
          style={{ display: "none" }}
        >
          <div className="bar" />
        </div>
        <p id="r2r-batch-status" className="workflow-status-line" />
      </section>
    );
  return (
    <section className="batch-run-panel">
      <p id="batch-run-summary" className="batch-run-summary">
        {text("No inputs selected.", "尚未选择输入动作。")}
      </p>
      <button id="batch-run" type="button" className="btn" disabled>
        {text("Start batch task", "开始批量任务")}
      </button>
      <p id="batch-disabled-reason" className="disabled-action-reason">
        {text(
          "Add motions and select a target robot first.",
          "请先添加动作并选择目标机器人。",
        )}
      </p>
      <div id="batch-progress-stack" className="batch-progress-stack hidden">
        <div id="batch-progress-total" className="progress">
          <div className="bar" />
        </div>
        <div id="batch-progress-clip" className="progress">
          <div className="bar" />
        </div>
      </div>
      <p id="batch-status" className="workflow-status-line" />
      <div id="batch-result-card" className="batch-result-card hidden">
        <strong id="batch-result-title">
          {text("Batch complete", "批量任务完成")}
        </strong>
        <p id="batch-result-summary" />
        <button
          id="batch-result-download"
          type="button"
          className="btn secondary small"
        >
          {text("Download ZIP", "下载 ZIP")}
        </button>
        <button id="batch-result-retry" type="button" hidden>
          {text("Retry failed only", "仅重试失败项")}
        </button>
        <button id="batch-result-tasks" type="button">
          {text("Open Tasks", "打开任务面板")}
        </button>
      </div>
      <div id="batch-failures" className="batch-failures hidden" />
    </section>
  );
}

function VideoBatchInspector({
  locale,
  model,
}: {
  locale: WorkspaceLocale;
  model: VideoBatchModel;
}) {
  const text = useLocaleText(locale);
  return (
    <div className="batch-mode-content v2m-batch-mode-content">
      <div className="batch-step-summary">
        <span>{text("1. Videos", "1. 视频")}</span>
        <strong>
          <span id="v2m-batch-inspector-count">{model.videos.length}</span>{" "}
          {text("videos", "个")}
        </strong>
      </div>
      <details className="video-workflow-step" open>
        <summary className="video-workflow-step-summary">
          {text("2. Environment", "2. 运行环境")}
        </summary>
        <div className="video-workflow-step-body">
          <select id="v2m-batch-runtime" className="search" disabled>
            <option>GVHMR Official</option>
          </select>
          <button
            id="v2m-batch-confirm"
            type="button"
            className="btn workflow-load-button"
            disabled={
              model.runtimeChecking ||
              model.runtime?.ready !== true ||
              model.environmentConfirmed
            }
            onClick={model.confirmEnvironment}
          >
            {model.environmentConfirmed
              ? text("Confirmed", "已确认")
              : text("Confirm environment", "确认运行环境")}
          </button>
          <p id="v2m-batch-runtime-status" className="workflow-status-line">
            {model.runtimeChecking
              ? text("Checking GVHMR…", "正在检查 GVHMR……")
              : model.runtime?.ready
                ? text(
                    "GVHMR official runtime is ready.",
                    "GVHMR 官方运行环境已就绪。",
                  )
                : model.runtime?.missing?.[0] ||
                  model.runtimeError ||
                  text(
                    "GVHMR runtime is unavailable.",
                    "GVHMR 运行环境不可用。",
                  )}
          </p>
          <button
            type="button"
            className="btn secondary small"
            disabled={model.runtimeChecking || model.busy}
            onClick={() => void model.refreshRuntime()}
          >
            {text("Check again", "重新检查")}
          </button>
        </div>
      </details>
      <details className="video-workflow-step" open>
        <summary className="video-workflow-step-summary">
          {text("3. Generate motions", "3. 生成动作")}
        </summary>
        <div className="video-workflow-step-body">
          <label className="workflow-checkbox-row">
            <input
              id="v2m-batch-static-camera"
              type="checkbox"
              checked={model.staticCamera}
              onChange={(event) =>
                model.setStaticCamera(event.currentTarget.checked)
              }
            />
            <span>{text("Static camera", "静态相机")}</span>
          </label>
          <input
            id="v2m-batch-focal-length"
            className="search"
            placeholder="Auto"
            value={model.focalLength}
            onChange={(event) =>
              model.setFocalLength(event.currentTarget.value)
            }
          />
          <button
            id="v2m-batch-run"
            type="button"
            className="btn"
            disabled={!model.canRun}
            onClick={() => void model.runBatch()}
          >
            {model.busy
              ? text("Generating…", "生成中……")
              : text("Start V2M batch", "开始 V2M 批量任务")}
          </button>
          <div
            id="v2m-batch-progress"
            className="progress"
            role="progressbar"
            aria-valuemin={0}
            aria-valuemax={100}
            aria-valuenow={Math.round(model.aggregateProgress * 100)}
          >
            <div
              className="bar"
              style={{ width: `${Math.round(model.aggregateProgress * 100)}%` }}
            />
          </div>
          <p id="v2m-batch-status" className="workflow-status-line">
            {model.statusMessage ||
              text(
                "Generated motions are added to H2R batch automatically.",
                "生成的动作会自动加入 H2R 批量清单。",
              )}
          </p>
        </div>
      </details>
    </div>
  );
}
